FROM uws/python-2203

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="230208"

USER root:root
WORKDIR /root

ENV USER root
ENV HOME /root

RUN /root/bin/apt-install.sh shellcheck git

RUN install -v -d -m 0750 -o uws -g uws /srv/deploy/Buildpack

USER uws:uws
WORKDIR /home/uws

ENV USER uws
ENV HOME /home/uws

RUN mkdir -vp -m 0750 ~/tmp

WORKDIR /srv/deploy/Buildpack
