FROM uws/meteor-2203

LABEL mantainer="Jeremías Casteglione <jeremias@talkingpts.org>"
LABEL version="220411"

ARG APP
ENV APP ${APP}

RUN install -v -d -m 0750 ${HOME}/${APP}/

COPY --chown=uws:uws ./src/ ${HOME}/${APP}/
